//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int EmployeeId { get; set; }
        public string ShippingProvider { get; set; }
        public int TrackingNumber { get; set; }
        public byte[] DateOut { get; set; }
        public System.DateTime ExpectedArrivalData { get; set; }
        public decimal TotalShippingCost { get; set; }
    }
}
